create table if not exists public.users (id text primary key,email text,tier text not null default 'guest' check (tier in ('guest','free','paid')),created double precision not null);
create table if not exists public.events (id bigint generated by default as identity primary key,user_id text not null references public.users(id) on delete cascade,event text not null,story_id text,rating text,created double precision not null);
create index if not exists events_user_event_created_idx on public.events(user_id,event,created desc);
create table if not exists public.saved (user_id text not null references public.users(id) on delete cascade,story_id text not null,title text not null,provenance text,text text not null,created double precision not null,primary key(user_id,story_id));
create table if not exists public.recent (id bigint generated by default as identity primary key,user_id text not null references public.users(id) on delete cascade,story_id text not null,title text not null,provenance text,text text not null,created double precision not null);
create index if not exists recent_user_created_idx on public.recent(user_id,created desc);
create table if not exists public.reflections (id bigint generated by default as identity primary key,user_id text not null references public.users(id) on delete cascade,story_id text,text text not null,created double precision not null);
create table if not exists public.prefs (user_id text primary key references public.users(id) on delete cascade,mode text not null default 'read',voice text not null default 'default',sound boolean not null default true,faith text not null default 'neutral',language text not null default 'English',history boolean not null default true);
alter table public.users enable row level security;
alter table public.events enable row level security;
alter table public.saved enable row level security;
alter table public.recent enable row level security;
alter table public.reflections enable row level security;
alter table public.prefs enable row level security;


-- v0.11 real account profile migration
alter table public.users add column if not exists first_name text;
alter table public.users add column if not exists country text;
